#!/bin/bash

set -e

echo "Starting hyprmoncfg installation from source"

echo "Installing Go and Git..."
sudo apt update
sudo apt install -y golang git

echo "Cloning hyprmoncfg repository"
TEMP_DIR=$(mktemp -d)
git clone https://github.com/crmne/hyprmoncfg.git "$TEMP_DIR"
cd "$TEMP_DIR"

echo "Building binaries"
go build -o bin/hyprmoncfg ./cmd/hyprmoncfg
go build -o bin/hyprmoncfgd ./cmd/hyprmoncfgd

echo "Moving binaries to ~/.local/bin"
mkdir -p "$HOME/.local/bin"
install -Dm755 bin/hyprmoncfg  "$HOME/.local/bin/hyprmoncfg"
install -Dm755 bin/hyprmoncfgd "$HOME/.local/bin/hyprmoncfgd"

echo "Setting up systemd user service"
mkdir -p "$HOME/.config/systemd/user"
cp packaging/systemd/hyprmoncfgd.local.service "$HOME/.config/systemd/user/hyprmoncfgd.service"

systemctl --user daemon-reload
systemctl --user enable --now hyprmoncfgd

HYPR_CONF="$HOME/.config/hypr/hyprland.conf"
SOURCE_LINE="source= ~/.config/hypr/monitors.conf"

if grep -q "monitors.conf" "$HYPR_CONF"; then
    echo "Source line already exists in hyprland.conf"
else
    echo "Adding source line to $HYPR_CONF"
    echo -e "\n# Monitor Config (generated by hyprmoncfg)\n$SOURCE_LINE" >> "$HYPR_CONF"
fi

# 7. Cleanup
echo "Cleaning up temporary files"
rm -rf "$TEMP_DIR"

echo "-------------------------------------------------------"
echo "Installation Complete!"
echo "Run 'hyprmoncfg' to configure your monitors."
echo "-------------------------------------------------------"
