# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141414)
$foreground = rgb(F4EBEB)
$color0 = rgb(3C3C3C)
$color1 = rgb(A24642)
$color2 = rgb(A24642)
$color3 = rgb(A24642)
$color4 = rgb(A2706D)
$color5 = rgb(A89594)
$color6 = rgb(A89595)
$color7 = rgb(E7DBDA)
$color8 = rgb(A29999)
$color9 = rgb(D85E58)
$color10 = rgb(D85E58)
$color11 = rgb(D85E58)
$color12 = rgb(D89692)
$color13 = rgb(E0C7C6)
$color14 = rgb(E0C7C6)
$color15 = rgb(E7DBDA)
